# Generated by Django 4.1.4 on 2022-12-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='标题')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者')),
                ('publishDate', models.DateField(blank=True, null=True, verbose_name='发行时间')),
                ('rating', models.SmallIntegerField(blank=True, null=True, verbose_name='评分')),
                ('type', models.CharField(blank=True, max_length=200, null=True, verbose_name='种类')),
                ('path', models.CharField(blank=True, max_length=3000, null=True, verbose_name='路径')),
            ],
        ),
        migrations.CreateModel(
            name='BookLibPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folderPath', models.CharField(blank=True, max_length=3000, null=True, verbose_name='文件夹路径')),
            ],
        ),
    ]
